[functions.analyze-document]
enabled = true
verify_jwt = true
import_map = "./functions/analyze-document/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/analyze-document/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/analyze-document/*.html" ]

[functions.paystack-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/paystack-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/paystack-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/paystack-webhook/*.html" ]

[functions.calendar-oauth]
enabled = true
verify_jwt = false
import_map = "./functions/calendar-oauth/deno.json"
entrypoint = "./functions/calendar-oauth/index.ts"

[functions.calendar-available-slots]
enabled = true
verify_jwt = true
import_map = "./functions/calendar-available-slots/deno.json"
entrypoint = "./functions/calendar-available-slots/index.ts"

[functions.calendar-create-event]
enabled = true
verify_jwt = true
import_map = "./functions/calendar-create-event/deno.json"
entrypoint = "./functions/calendar-create-event/index.ts"

[functions.email-gmail-oauth]
  verify_jwt = false

[functions.email-gmail-list-messages]
  verify_jwt = false

[functions.verifyid-credit-report]
enabled = true
verify_jwt = true
import_map = "./functions/verifyid-credit-report/deno.json"
# Entrypoint for the function
entrypoint = "./functions/verifyid-credit-report/index.ts"

[functions.slack-notifications]
enabled = true
verify_jwt = true
import_map = "./functions/slack-notifications/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/slack-notifications/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/slack-notifications/*.html" ]
