// Mock credit report data based on actual VerifyID API response structure
export const data = {
	status: 'Success',
	risk_type: 'AVERAGE RISK',
	risk_color: '245,236,86',
	credit_score: 636,
	thin_file_indicator: false,
	score_version: '2',
	score_type: 'CPA',
	decline_reasons: [
		'CA42-Balance or Limit of 0 on All Accounts',
		'CA18-Recent Arrears Level on Selected Accounts',
		'CA52-No Revolving Accounts Held',
	],
	enquiry_counts: {
		ADDR: '5',
		ADMORDS: '0',
		COLLECTIONS: '0',
		DMATCHES: '1',
		JUDGE: '0',
		NOTICES: '0',
		PMATCHES: '0',
		PREV_ENQ: '7',
		TPHONE: '5',
		EMPLOYERS: '5',
		TRACE: '0',
		FRAUDALERT: '0',
		CPACC: '3',
		NLRACC: '0',
		PUB_DEF: '0',
		CODIX: '0',
		COMPUSCORE: '1',
		DEEDS_COUNT: '1',
		BONDS_COUNT: '0',
		DIRECTORS: '4',
		CS_ADVERSE: '0',
	},
	accounts: [
		{
			SUBSCRIBER_NAME: 'FNB FUSION',
			ACCOUNT_TYPE_DESC: 'Single Credit Facility',
			OPEN_DATE: '03-09-2012',
			STATUS_CODE_DESC: 'PAID UP',
			PAYMENT_HISTORY: '000000000000000000??????',
		},
	],
	public_records: {
		judgements: [],
		notices: [],
		collections: [],
	},
	payment_history: true,
	report_date: new Date().toISOString(),
};
